#pragma once
#include <vector>
#include <string>
#include <iostream>
#include <assert.h>
#include <cstring>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <fcntl.h>
#include <signal.h>
#include <sys/wait.h>
#include <functional>
#include <sys/epoll.h>
#include <unordered_map>
#include <utility>
#include <mutex>
#include <thread>
#include <atomic>
#include <sys/eventfd.h>
#include <sys/timerfd.h>
#include <condition_variable>
#include <fstream>
#include <sys/stat.h>
#include <regex>